name: Python application test with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run tests with coverage
        run: |
          coverage run --source=lambdas -m unittest maha_nhtsa_to_s3_test.py
          coverage run --source=lambdas -a -m unittest maha_s3_to_mysql_test.py
          coverage run --source=lambdas -a -m unittest maha_db_to_frontend_test.py
          coverage run --source=lambdas -a -m unittest FetchUserReviews_test.py
          coverage run --source=lambdas -a -m unittest userReviewsPublish_test.py
          coverage report
